services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: submitty_web
    ports:
      - "8080:80"
    networks:
      - submitty_network

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: submitty_worker
    ports:
      - "9090:9090"
    networks:
      - submitty_network

networks:
  submitty_network:
    driver: bridge
